---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teste
  name: teste
  namespace: teste
spec:
  selector:
    matchLabels:
      app: teste
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: teste
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: general
      containers:
      - name: teste
        image: nginx:latest
        resources:
          limits:
            cpu: 200m
            memory: 256Mi